# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33a1f84c26f2c4c5e36f1e01cac8033251e9576e8878eb77eedbf84b20b3158edcfa3f7735378377c7800eade71681db9641189d5b0fce690c721ac2af598b37

test:
  secret_key_base: 4c73cb8021fd4d64aef78b73b631e5e88817b6b11bb5199edac62ee3fa267bb3ae46a997e9b97b848e7692943c5c8593b206d8900882bcdadd19d8869f5a72c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
